name: notify 
on: 
  push: 
      branches: 
            - master 
                  paths: 
                        - 'docs/**' 
                                - 'bin/**' 
                  jobs: 
                    notify: 
                        runs-on: ubuntu-latest 
                            steps: 
                                  - uses: actions/checkout@v1 
                                          - name: Send notification to Slack when master/docs has been updated 
                                                    uses: pullreminders/slack-action@v1 
                                                            with: 
                                                                        args: '{\"channel\":\"bot_test\", \"text\":\"flywheel_standardが変更されたよ\"}' 
                                                                        env: 
                                                                                 SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
